;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-paren
	electric-pair-delete-pair
	indent-for-tab-command
	))

(setq mc/cmds-to-run-once
      '(
	))
