#+TITLE: Org-babel Emacs configuration
#+AUTHOR: Klementiev Dmitry <klementievd08@yandex.ru>

Org Babel Emacs configuration.

Something like executable Wiki.

* Fundamental things of my configuration

Remove backup files. Remove warnings and errors from native compilation
#+begin_src emacs-lisp
  (setq make-backup-files nil)
  (setq native-comp-async-report-warnings-errors 'silent)
#+end_src

Do some appearance stuff. Setup cursor and remove UI blobs
#+begin_src emacs-lisp
  ;; Some appearance stuff
  (set-default 'cursor-type '(bar . 1))
  (blink-cursor-mode 0)
  (setq-default cursor-in-non-selected-windows nil)
  (setq bookmark-set-fringe-mark nil)

  (with-eval-after-load 'menu-bar
    (menu-bar-mode 0))
  (with-eval-after-load 'tool-bar
    (tool-bar-mode 0))
  (with-eval-after-load 'scroll-bar
    (scroll-bar-mode 0))
  (with-eval-after-load 'fringe
    (fringe-mode 8))
#+end_src

Face/Frame configuration. Setup fonts and cool built-in Emacs UI things
/Maybe I don't need to use relative line numbers/
#+begin_src emacs-lisp
  (defun load-face-attributes ()
    (set-face-attribute 'default nil :font "JetBrains Mono" :height 130)
    (set-face-attribute 'fixed-pitch nil :font "JetBrains Mono" :height 130)
    (set-face-attribute 'variable-pitch nil :font "JetBrains Mono" :height 130 :weight 'regular))

  (defun load-face-attributes-to-frame (frame)
    (select-frame frame)
    (load-face-attributes))

  (if (daemonp)
      (add-hook 'after-make-frame-functions #'load-face-attributes-to-frame)
    (load-face-attributes))

  (column-number-mode)
  (setq-default display-line-numbers 'relative) ; CHECKTHIS
  (global-display-line-numbers-mode t)
#+end_src

Initialize =straight.el=
#+begin_src emacs-lisp
  ;; Initialize straight.el
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

Display startup time. /(I use emacs as daemon and I don't really need it)/
#+begin_src emacs-lisp
  ;; Startup time
  (let ((emacs-start-time (current-time)))
    (add-hook 'emacs-startup-hook
              (lambda ()
                (let ((elapsed (float-time (time-subtract (current-time) emacs-start-time))))
                  (message "[Emacs initialized in %.3fs]" elapsed)))))
#+end_src

* Features. I call it Features

A lot of features inspired from [[https://git.sr.ht/~abcdw/rde][Guix RDE]]

** Installing packages

Yeap. I install all packages in one code block at one time. I like it

*** Appearance related packages

#+begin_src emacs-lisp
  (straight-use-package 'kaolin-themes)
  (straight-use-package 'monokai-pro-theme)
  (straight-use-package 'rainbow-delimiters)
  (straight-use-package 'rainbow-mode)
#+end_src

*** Good text editing

#+begin_src emacs-lisp
  (straight-use-package 'smartparens)
#+end_src

*** Completion and other mini-buffer stuff

#+begin_src emacs-lisp
  (straight-use-package 'vertico)
  (straight-use-package 'mini-frame)
  (straight-use-package 'orderless)
  (straight-use-package 'marginalia)
  (straight-use-package 'pcmpl-args)
  (straight-use-package 'cape)
  (straight-use-package 'consult)
  (straight-use-package 'embark)

  (straight-use-package 'corfu)
  ;; (straight-use-package 'corfu-doc)
  ;; (straight-use-package 'corfu-candidate-overlay)
#+end_src

*** Specific modes for files

I adding auto-mode-alist here. I don't need to use for it separated page

#+begin_src emacs-lisp
  (straight-use-package 'yuck-mode)
  (autoload 'yuck-mode "yuck-mode" nil t)
  (add-to-list 'auto-mode-alist '("\\.yuck\\'" . yuck-mode))

  (straight-use-package 'scss-mode)
  (autoload 'scss-mode "scss-mode" nil t)
  (add-to-list 'auto-mode-alist '("\\.scss\\'" . scss-mode))

  (straight-use-package 'go-mode)
  (autoload 'go-mode "go-mode" nil t)
  (add-to-list 'auto-mode-alist '("\\.go\\'" . go-mode))

  (straight-use-package 'zig-mode)
  (autoload 'zig-mode "zig-mode" nil t)
  (add-to-list 'auto-mode-alist '("\\.zig\\'" . zig-mode))
#+end_src

*** IDE packages (and all other packages -_-)

Maybe I don't need =eat= package. Replacements:
- vterm
- coterm
- eshell

#+begin_src emacs-lisp
  (straight-use-package
   '(eat :type git
         :host codeberg
         :repo "akib/emacs-eat"
         :files ("*.el" ("term" "term/*.el") "*.texi"
                 "*.ti" ("terminfo/e" "terminfo/e/*")
                 ("terminfo/65" "terminfo/65/*")
                 ("integration" "integration/*")
                 (:exclude ".dir-locals.el" "*-tests.el"))))

  (straight-use-package
   '(lsp-bridge
     :type git
     :host github
     :repo "manateelazycat/lsp-bridge"))
  
  (straight-use-package
   '(lsp-booster
     :type git
     :host github
     :repo "blahgeek/emacs-lsp-booster"))
#+end_src

** Appearance feature

TODO
