#+TITLE: Excellent Emacs configuration with Nix
#+DESCRIPTION: Inspired by `rde' guix-distribution
#+AUTHOR: Klementiev Dmitry <klementievd08@yandex.ru>

This is main part of my system configuration because I do a lot of things in GNU Emacs.

* Structure of Emacs configuration

- =default.nix= - the Emacs package. In this file we enabling native-compilation, pgtk and compile packages.
- =home.nix= - General Emacs configuration file. In this file we define =early-init.el= and general configuration. Also in home nix file we import other features
- =features/*.nix= - Features folders. Contain nix source files with a lot of features for your Emacs configuration
- =config/*.el= - ELisp source files (maybe rename from =config= to =elisp=)

* Why not Guix?

For now unique advantages of Guix is not enough to move.

* Roadmap

- [X] Emacs (pgtk, native-comp)
- [X] Appearance
- [X] Eshell
- [ ] Vterm
- [ ] All the icons
- [ ] Completion
- [ ] Vertico
- [ ] Corfu
- [ ] Eglot
- [ ] Flymake
- [ ] Elisp
- [ ] Git
- [ ] Org
- [ ] Which-Key
- [ ] Smartparens
- [ ] Telega
- [ ] LSP mode
- [ ] DAP mode
- [ ] Flycheck
- [ ] Yasnippets
- [ ] Company and Company Box
- [ ] App launcher
